2025-03-05 21:30:36,659 INFO    Thread-20 (_run_job):30544 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 21:30:36,659 INFO    Thread-20 (_run_job):30544 [wandb_setup.py:_flush():67] Configure stats pid to 30544
2025-03-05 21:30:36,659 INFO    Thread-20 (_run_job):30544 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 21:30:36,659 INFO    Thread-20 (_run_job):30544 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 21:30:36,660 INFO    Thread-20 (_run_job):30544 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 21:30:36,660 INFO    Thread-20 (_run_job):30544 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_213036-iy2n6va1\logs\debug.log
2025-03-05 21:30:36,660 INFO    Thread-20 (_run_job):30544 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_213036-iy2n6va1\logs\debug-internal.log
2025-03-05 21:30:36,660 INFO    Thread-20 (_run_job):30544 [wandb_init.py:init():761] calling init triggers
2025-03-05 21:30:36,660 INFO    Thread-20 (_run_job):30544 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'tanh', 'batch_size': 64, 'epochs': 5, 'hidden_layers': 3, 'hidden_size': 64, 'learning_rate': 0.0001, 'optimizer': 'nadam', 'weight_decay': 0.5, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-05 21:30:36,660 INFO    Thread-20 (_run_job):30544 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 21:30:36,661 ERROR   Thread-20 (_run_job):30544 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 21:30:36,668 INFO    Thread-20 (_run_job):30544 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/DLA1/rf8dkt5h
2025-03-05 21:30:37,373 INFO    Thread-23 (_run_job):30544 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 21:30:37,373 INFO    Thread-23 (_run_job):30544 [wandb_setup.py:_flush():67] Configure stats pid to 30544
2025-03-05 21:30:37,373 INFO    Thread-23 (_run_job):30544 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 21:30:37,373 INFO    Thread-23 (_run_job):30544 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 21:30:37,373 INFO    Thread-23 (_run_job):30544 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 21:30:37,373 INFO    Thread-23 (_run_job):30544 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_213037-zrau82ph\logs\debug.log
2025-03-05 21:30:37,373 INFO    Thread-23 (_run_job):30544 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_213037-zrau82ph\logs\debug-internal.log
2025-03-05 21:30:37,373 INFO    Thread-23 (_run_job):30544 [wandb_init.py:init():761] calling init triggers
2025-03-05 21:30:37,373 INFO    Thread-23 (_run_job):30544 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 32, 'epochs': 5, 'hidden_layers': 4, 'hidden_size': 128, 'learning_rate': 0.001, 'optimizer': 'adam', 'weight_decay': 0.0005, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-05 21:30:37,375 INFO    Thread-23 (_run_job):30544 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 21:30:37,375 ERROR   Thread-23 (_run_job):30544 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 21:30:37,382 INFO    Thread-23 (_run_job):30544 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/DLA1/rf8dkt5h
2025-03-05 21:30:47,479 INFO    Thread-26 (_run_job):30544 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 21:30:47,479 INFO    Thread-26 (_run_job):30544 [wandb_setup.py:_flush():67] Configure stats pid to 30544
2025-03-05 21:30:47,479 INFO    Thread-26 (_run_job):30544 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 21:30:47,479 INFO    Thread-26 (_run_job):30544 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 21:30:47,479 INFO    Thread-26 (_run_job):30544 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 21:30:47,480 INFO    Thread-26 (_run_job):30544 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_213047-n24r3p2a\logs\debug.log
2025-03-05 21:30:47,480 INFO    Thread-26 (_run_job):30544 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_213047-n24r3p2a\logs\debug-internal.log
2025-03-05 21:30:47,480 INFO    Thread-26 (_run_job):30544 [wandb_init.py:init():761] calling init triggers
2025-03-05 21:30:47,480 INFO    Thread-26 (_run_job):30544 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 32, 'epochs': 10, 'hidden_layers': 3, 'hidden_size': 128, 'learning_rate': 0.001, 'optimizer': 'adam', 'weight_decay': 0, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-05 21:30:47,480 INFO    Thread-26 (_run_job):30544 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 21:30:47,481 ERROR   Thread-26 (_run_job):30544 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 21:30:47,487 INFO    Thread-26 (_run_job):30544 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/DLA1/rf8dkt5h
2025-03-05 21:30:48,395 INFO    Thread-29 (_run_job):30544 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 21:30:48,395 INFO    Thread-29 (_run_job):30544 [wandb_setup.py:_flush():67] Configure stats pid to 30544
2025-03-05 21:30:48,395 INFO    Thread-29 (_run_job):30544 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 21:30:48,395 INFO    Thread-29 (_run_job):30544 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 21:30:48,395 INFO    Thread-29 (_run_job):30544 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 21:30:48,395 INFO    Thread-29 (_run_job):30544 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_213048-pa6zm83e\logs\debug.log
2025-03-05 21:30:48,396 INFO    Thread-29 (_run_job):30544 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_213048-pa6zm83e\logs\debug-internal.log
2025-03-05 21:30:48,396 INFO    Thread-29 (_run_job):30544 [wandb_init.py:init():761] calling init triggers
2025-03-05 21:30:48,396 INFO    Thread-29 (_run_job):30544 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'tanh', 'batch_size': 64, 'epochs': 5, 'hidden_layers': 5, 'hidden_size': 128, 'learning_rate': 0.0001, 'optimizer': 'adam', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-05 21:30:48,396 INFO    Thread-29 (_run_job):30544 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 21:30:48,396 ERROR   Thread-29 (_run_job):30544 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 21:30:48,402 INFO    Thread-29 (_run_job):30544 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/DLA1/rf8dkt5h
2025-03-05 21:30:58,438 INFO    MainThread:30544 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 21:30:58,439 INFO    MainThread:30544 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 21:31:09,263 INFO    MainThread:30544 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 21:31:09,339 INFO    MainThread:30544 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 21:31:09,340 INFO    MainThread:30544 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 21:31:10,077 INFO    MainThread:30544 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 21:31:10,138 INFO    MainThread:30544 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_213110-pa6zm83e\logs\debug.log
2025-03-05 21:31:10,138 INFO    MainThread:30544 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_213110-pa6zm83e\logs\debug-internal.log
2025-03-05 21:31:10,139 INFO    MainThread:30544 [wandb_init.py:init():761] calling init triggers
2025-03-05 21:31:10,139 INFO    MainThread:30544 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'tanh', 'batch_size': 64, 'epochs': 5, 'hidden_layers': 5, 'hidden_size': 128, 'learning_rate': 0.0001, 'optimizer': 'adam', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-05 21:31:10,139 INFO    MainThread:30544 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 21:31:10,140 ERROR   MainThread:30544 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 21:31:10,622 INFO    MainThread:30544 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 21:31:10,622 INFO    MainThread:30544 [wandb_init.py:_pause_backend():564] pausing backend
