2025-03-05 21:29:58,235 INFO    MainThread:30544 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 21:29:58,235 INFO    MainThread:30544 [wandb_setup.py:_flush():67] Configure stats pid to 30544
2025-03-05 21:29:58,235 INFO    MainThread:30544 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 21:29:58,235 INFO    MainThread:30544 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 21:29:58,236 INFO    MainThread:30544 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 21:29:58,236 INFO    MainThread:30544 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_212958-rf8dkt5h\logs\debug.log
2025-03-05 21:29:58,236 INFO    MainThread:30544 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_212958-rf8dkt5h\logs\debug-internal.log
2025-03-05 21:29:58,236 INFO    MainThread:30544 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000027B5698DA90>
2025-03-05 21:29:58,237 INFO    MainThread:30544 [wandb_init.py:init():761] calling init triggers
2025-03-05 21:29:58,237 INFO    MainThread:30544 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-05 21:29:58,237 INFO    MainThread:30544 [wandb_init.py:init():784] starting backend
2025-03-05 21:29:58,237 INFO    MainThread:30544 [wandb_init.py:init():788] sending inform_init request
2025-03-05 21:29:58,254 INFO    MainThread:30544 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-03-05 21:29:58,254 INFO    MainThread:30544 [wandb_init.py:init():803] backend started and connected
2025-03-05 21:29:58,257 INFO    MainThread:30544 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-05 21:29:58,270 INFO    MainThread:30544 [wandb_init.py:init():896] updated telemetry
2025-03-05 21:29:58,319 INFO    MainThread:30544 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-05 21:30:00,251 INFO    MainThread:30544 [wandb_init.py:init():995] starting run threads in backend
2025-03-05 21:30:00,530 INFO    MainThread:30544 [wandb_run.py:_console_start():2377] atexit reg
2025-03-05 21:30:00,530 INFO    MainThread:30544 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-05 21:30:00,530 INFO    MainThread:30544 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-05 21:30:00,530 INFO    MainThread:30544 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-05 21:30:00,535 INFO    MainThread:30544 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-05 21:30:01,452 INFO    MainThread:30544 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 21:30:01,452 INFO    MainThread:30544 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 21:30:11,183 INFO    MainThread:30544 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 21:30:11,320 INFO    MainThread:30544 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 21:30:11,320 INFO    MainThread:30544 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 21:30:12,105 INFO    MainThread:30544 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 21:30:12,110 INFO    MainThread:30544 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 21:30:12,110 INFO    MainThread:30544 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 21:30:12,828 INFO    MainThread:30544 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 21:30:12,829 INFO    MainThread:30544 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 21:30:12,829 INFO    MainThread:30544 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 21:30:13,508 INFO    MainThread:30544 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 21:30:13,509 INFO    MainThread:30544 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 21:30:13,509 INFO    MainThread:30544 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 21:30:14,206 INFO    MainThread:30544 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 21:30:14,209 INFO    MainThread:30544 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 21:30:14,209 INFO    MainThread:30544 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 21:30:15,258 INFO    MainThread:30544 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 21:30:15,261 INFO    MainThread:30544 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 21:30:15,261 INFO    MainThread:30544 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 21:30:16,078 INFO    MainThread:30544 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 21:30:16,872 INFO    MainThread:30544 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 21:30:16,872 INFO    MainThread:30544 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 21:30:20,137 INFO    MainThread:30544 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 21:30:20,141 INFO    MainThread:30544 [pyagent.py:run():322] Starting sweep agent: entity=None, project=None, count=None
2025-03-05 21:30:20,990 WARNING MsgRouterThr:30544 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-05 21:30:20,992 INFO    MsgRouterThr:30544 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
2025-03-05 21:30:22,819 INFO    Thread-14 (_run_job):30544 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 21:30:22,820 INFO    Thread-14 (_run_job):30544 [wandb_setup.py:_flush():67] Configure stats pid to 30544
2025-03-05 21:30:22,820 INFO    Thread-14 (_run_job):30544 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 21:30:22,820 INFO    Thread-14 (_run_job):30544 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 21:30:22,820 INFO    Thread-14 (_run_job):30544 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 21:30:22,820 INFO    Thread-14 (_run_job):30544 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_213022-t6b93svz\logs\debug.log
2025-03-05 21:30:22,820 INFO    Thread-14 (_run_job):30544 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_213022-t6b93svz\logs\debug-internal.log
2025-03-05 21:30:22,820 INFO    Thread-14 (_run_job):30544 [wandb_init.py:init():761] calling init triggers
2025-03-05 21:30:22,820 INFO    Thread-14 (_run_job):30544 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 32, 'epochs': 10, 'hidden_layers': 3, 'hidden_size': 32, 'learning_rate': 0.0001, 'optimizer': 'nadam', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-05 21:30:22,820 INFO    Thread-14 (_run_job):30544 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 21:30:22,821 ERROR   Thread-14 (_run_job):30544 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 21:30:22,865 INFO    Thread-14 (_run_job):30544 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/DLA1/rf8dkt5h
2025-03-05 21:30:26,526 INFO    Thread-17 (_run_job):30544 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 21:30:26,526 INFO    Thread-17 (_run_job):30544 [wandb_setup.py:_flush():67] Configure stats pid to 30544
2025-03-05 21:30:26,526 INFO    Thread-17 (_run_job):30544 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 21:30:26,527 INFO    Thread-17 (_run_job):30544 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 21:30:26,527 INFO    Thread-17 (_run_job):30544 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 21:30:26,527 INFO    Thread-17 (_run_job):30544 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_213026-1hcuhmwe\logs\debug.log
2025-03-05 21:30:26,527 INFO    Thread-17 (_run_job):30544 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_213026-1hcuhmwe\logs\debug-internal.log
2025-03-05 21:30:26,527 INFO    Thread-17 (_run_job):30544 [wandb_init.py:init():761] calling init triggers
2025-03-05 21:30:26,527 INFO    Thread-17 (_run_job):30544 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 16, 'epochs': 10, 'hidden_layers': 4, 'hidden_size': 64, 'learning_rate': 0.001, 'optimizer': 'momentum', 'weight_decay': 0.0005, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-05 21:30:26,527 INFO    Thread-17 (_run_job):30544 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 21:30:26,528 ERROR   Thread-17 (_run_job):30544 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 21:30:26,535 INFO    Thread-17 (_run_job):30544 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/DLA1/rf8dkt5h
2025-03-05 21:30:36,659 INFO    Thread-20 (_run_job):30544 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 21:30:36,659 INFO    Thread-20 (_run_job):30544 [wandb_setup.py:_flush():67] Configure stats pid to 30544
2025-03-05 21:30:36,659 INFO    Thread-20 (_run_job):30544 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 21:30:36,659 INFO    Thread-20 (_run_job):30544 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 21:30:36,660 INFO    Thread-20 (_run_job):30544 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 21:30:36,660 INFO    Thread-20 (_run_job):30544 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_213036-iy2n6va1\logs\debug.log
2025-03-05 21:30:36,660 INFO    Thread-20 (_run_job):30544 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_213036-iy2n6va1\logs\debug-internal.log
2025-03-05 21:30:36,660 INFO    Thread-20 (_run_job):30544 [wandb_init.py:init():761] calling init triggers
2025-03-05 21:30:36,660 INFO    Thread-20 (_run_job):30544 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'tanh', 'batch_size': 64, 'epochs': 5, 'hidden_layers': 3, 'hidden_size': 64, 'learning_rate': 0.0001, 'optimizer': 'nadam', 'weight_decay': 0.5, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-05 21:30:36,660 INFO    Thread-20 (_run_job):30544 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 21:30:36,661 ERROR   Thread-20 (_run_job):30544 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 21:30:36,668 INFO    Thread-20 (_run_job):30544 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/DLA1/rf8dkt5h
2025-03-05 21:30:37,373 INFO    Thread-23 (_run_job):30544 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 21:30:37,373 INFO    Thread-23 (_run_job):30544 [wandb_setup.py:_flush():67] Configure stats pid to 30544
2025-03-05 21:30:37,373 INFO    Thread-23 (_run_job):30544 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 21:30:37,373 INFO    Thread-23 (_run_job):30544 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 21:30:37,373 INFO    Thread-23 (_run_job):30544 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 21:30:37,373 INFO    Thread-23 (_run_job):30544 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_213037-zrau82ph\logs\debug.log
2025-03-05 21:30:37,373 INFO    Thread-23 (_run_job):30544 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_213037-zrau82ph\logs\debug-internal.log
2025-03-05 21:30:37,373 INFO    Thread-23 (_run_job):30544 [wandb_init.py:init():761] calling init triggers
2025-03-05 21:30:37,373 INFO    Thread-23 (_run_job):30544 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 32, 'epochs': 5, 'hidden_layers': 4, 'hidden_size': 128, 'learning_rate': 0.001, 'optimizer': 'adam', 'weight_decay': 0.0005, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-05 21:30:37,375 INFO    Thread-23 (_run_job):30544 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 21:30:37,375 ERROR   Thread-23 (_run_job):30544 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 21:30:37,382 INFO    Thread-23 (_run_job):30544 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/DLA1/rf8dkt5h
2025-03-05 21:30:47,479 INFO    Thread-26 (_run_job):30544 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 21:30:47,479 INFO    Thread-26 (_run_job):30544 [wandb_setup.py:_flush():67] Configure stats pid to 30544
2025-03-05 21:30:47,479 INFO    Thread-26 (_run_job):30544 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 21:30:47,479 INFO    Thread-26 (_run_job):30544 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 21:30:47,479 INFO    Thread-26 (_run_job):30544 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 21:30:47,480 INFO    Thread-26 (_run_job):30544 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_213047-n24r3p2a\logs\debug.log
2025-03-05 21:30:47,480 INFO    Thread-26 (_run_job):30544 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_213047-n24r3p2a\logs\debug-internal.log
2025-03-05 21:30:47,480 INFO    Thread-26 (_run_job):30544 [wandb_init.py:init():761] calling init triggers
2025-03-05 21:30:47,480 INFO    Thread-26 (_run_job):30544 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 32, 'epochs': 10, 'hidden_layers': 3, 'hidden_size': 128, 'learning_rate': 0.001, 'optimizer': 'adam', 'weight_decay': 0, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-05 21:30:47,480 INFO    Thread-26 (_run_job):30544 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 21:30:47,481 ERROR   Thread-26 (_run_job):30544 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 21:30:47,487 INFO    Thread-26 (_run_job):30544 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/DLA1/rf8dkt5h
2025-03-05 21:30:48,395 INFO    Thread-29 (_run_job):30544 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 21:30:48,395 INFO    Thread-29 (_run_job):30544 [wandb_setup.py:_flush():67] Configure stats pid to 30544
2025-03-05 21:30:48,395 INFO    Thread-29 (_run_job):30544 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 21:30:48,395 INFO    Thread-29 (_run_job):30544 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 21:30:48,395 INFO    Thread-29 (_run_job):30544 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 21:30:48,395 INFO    Thread-29 (_run_job):30544 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_213048-pa6zm83e\logs\debug.log
2025-03-05 21:30:48,396 INFO    Thread-29 (_run_job):30544 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_213048-pa6zm83e\logs\debug-internal.log
2025-03-05 21:30:48,396 INFO    Thread-29 (_run_job):30544 [wandb_init.py:init():761] calling init triggers
2025-03-05 21:30:48,396 INFO    Thread-29 (_run_job):30544 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'tanh', 'batch_size': 64, 'epochs': 5, 'hidden_layers': 5, 'hidden_size': 128, 'learning_rate': 0.0001, 'optimizer': 'adam', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-05 21:30:48,396 INFO    Thread-29 (_run_job):30544 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 21:30:48,396 ERROR   Thread-29 (_run_job):30544 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 21:30:48,402 INFO    Thread-29 (_run_job):30544 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/DLA1/rf8dkt5h
2025-03-05 21:30:58,438 INFO    MainThread:30544 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 21:30:58,439 INFO    MainThread:30544 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 21:31:09,263 INFO    MainThread:30544 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 21:31:09,339 INFO    MainThread:30544 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 21:31:09,340 INFO    MainThread:30544 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 21:31:10,077 INFO    MainThread:30544 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 21:31:10,138 INFO    MainThread:30544 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_213110-pa6zm83e\logs\debug.log
2025-03-05 21:31:10,138 INFO    MainThread:30544 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_213110-pa6zm83e\logs\debug-internal.log
2025-03-05 21:31:10,139 INFO    MainThread:30544 [wandb_init.py:init():761] calling init triggers
2025-03-05 21:31:10,139 INFO    MainThread:30544 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'tanh', 'batch_size': 64, 'epochs': 5, 'hidden_layers': 5, 'hidden_size': 128, 'learning_rate': 0.0001, 'optimizer': 'adam', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-05 21:31:10,139 INFO    MainThread:30544 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 21:31:10,140 ERROR   MainThread:30544 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 21:31:10,622 INFO    MainThread:30544 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 21:31:10,622 INFO    MainThread:30544 [wandb_init.py:_pause_backend():564] pausing backend
