2025-03-05 21:46:02,976 INFO    MainThread:27272 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 21:46:02,976 INFO    MainThread:27272 [wandb_setup.py:_flush():67] Configure stats pid to 27272
2025-03-05 21:46:02,976 INFO    MainThread:27272 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 21:46:02,976 INFO    MainThread:27272 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 21:46:02,976 INFO    MainThread:27272 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 21:46:02,977 INFO    MainThread:27272 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_214602-07etksak\logs\debug.log
2025-03-05 21:46:02,977 INFO    MainThread:27272 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_214602-07etksak\logs\debug-internal.log
2025-03-05 21:46:02,977 INFO    MainThread:27272 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002037B6D7B90>
2025-03-05 21:46:02,977 INFO    MainThread:27272 [wandb_init.py:init():761] calling init triggers
2025-03-05 21:46:02,977 INFO    MainThread:27272 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-05 21:46:02,977 INFO    MainThread:27272 [wandb_init.py:init():784] starting backend
2025-03-05 21:46:02,977 INFO    MainThread:27272 [wandb_init.py:init():788] sending inform_init request
2025-03-05 21:46:02,994 INFO    MainThread:27272 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-03-05 21:46:02,996 INFO    MainThread:27272 [wandb_init.py:init():803] backend started and connected
2025-03-05 21:46:02,998 INFO    MainThread:27272 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-05 21:46:03,005 INFO    MainThread:27272 [wandb_init.py:init():896] updated telemetry
2025-03-05 21:46:03,050 INFO    MainThread:27272 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-05 21:46:05,164 INFO    MainThread:27272 [wandb_init.py:init():995] starting run threads in backend
2025-03-05 21:46:05,417 INFO    MainThread:27272 [wandb_run.py:_console_start():2377] atexit reg
2025-03-05 21:46:05,417 INFO    MainThread:27272 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-05 21:46:05,417 INFO    MainThread:27272 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-05 21:46:05,417 INFO    MainThread:27272 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-05 21:46:05,420 INFO    MainThread:27272 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-05 21:46:06,615 INFO    MainThread:27272 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 21:46:06,615 INFO    MainThread:27272 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 21:46:07,849 INFO    MainThread:27272 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 21:46:07,854 INFO    MainThread:27272 [pyagent.py:run():322] Starting sweep agent: entity=da24m014-iit-madras, project=DLA1, count=None
2025-03-05 21:46:08,266 ERROR   MainThread:27272 [internal_api.py:execute():402] 404 response executing GraphQL.
2025-03-05 21:46:08,266 ERROR   MainThread:27272 [internal_api.py:execute():403] {"errors":[{"message":"could not find sweep da24m014-iit-madras/DLA1/l8d9h7hz during createAgent","path":["createAgent"]}],"data":{"createAgent":null}}
2025-03-05 21:46:08,959 INFO    MainThread:27272 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 21:46:08,959 INFO    MainThread:27272 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 21:46:45,609 INFO    MainThread:27272 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 21:46:45,613 INFO    MainThread:27272 [pyagent.py:run():322] Starting sweep agent: entity=da24m014-iit-madras, project=DLA1, count=None
2025-03-05 21:46:46,461 ERROR   MainThread:27272 [internal_api.py:execute():402] 404 response executing GraphQL.
2025-03-05 21:46:46,461 ERROR   MainThread:27272 [internal_api.py:execute():403] {"errors":[{"message":"could not find sweep da24m014-iit-madras/DLA1/l8d9h7hz during createAgent","path":["createAgent"]}],"data":{"createAgent":null}}
2025-03-05 21:46:46,638 INFO    MainThread:27272 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 21:46:46,639 INFO    MainThread:27272 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 21:46:54,748 INFO    MainThread:27272 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 21:46:56,564 INFO    MainThread:27272 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 21:46:56,565 INFO    MainThread:27272 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 21:46:57,345 INFO    MainThread:27272 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 21:46:57,349 INFO    MainThread:27272 [pyagent.py:run():322] Starting sweep agent: entity=da24m014-iit-madras, project=DLA1, count=None
2025-03-05 21:46:58,278 WARNING MsgRouterThr:27272 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-05 21:46:58,279 INFO    MsgRouterThr:27272 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
2025-03-05 21:47:00,142 INFO    Thread-14 (_run_job):27272 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 21:47:00,142 INFO    Thread-14 (_run_job):27272 [wandb_setup.py:_flush():67] Configure stats pid to 27272
2025-03-05 21:47:00,142 INFO    Thread-14 (_run_job):27272 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 21:47:00,142 INFO    Thread-14 (_run_job):27272 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 21:47:00,142 INFO    Thread-14 (_run_job):27272 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 21:47:00,142 INFO    Thread-14 (_run_job):27272 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_214700-f9t8url2\logs\debug.log
2025-03-05 21:47:00,143 INFO    Thread-14 (_run_job):27272 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_214700-f9t8url2\logs\debug-internal.log
2025-03-05 21:47:00,143 INFO    Thread-14 (_run_job):27272 [wandb_init.py:init():761] calling init triggers
2025-03-05 21:47:00,143 INFO    Thread-14 (_run_job):27272 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 16, 'epochs': 5, 'hidden_layers': 4, 'hidden_size': 128, 'learning_rate': 0.001, 'optimizer': 'adam', 'weight_decay': 0.0005, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-05 21:47:00,143 INFO    Thread-14 (_run_job):27272 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 21:47:00,143 ERROR   Thread-14 (_run_job):27272 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 21:47:00,153 INFO    Thread-14 (_run_job):27272 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/DLA1/07etksak
2025-03-05 21:47:03,833 INFO    Thread-17 (_run_job):27272 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 21:47:03,833 INFO    Thread-17 (_run_job):27272 [wandb_setup.py:_flush():67] Configure stats pid to 27272
2025-03-05 21:47:03,833 INFO    Thread-17 (_run_job):27272 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 21:47:03,833 INFO    Thread-17 (_run_job):27272 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 21:47:03,833 INFO    Thread-17 (_run_job):27272 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 21:47:03,833 INFO    Thread-17 (_run_job):27272 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_214703-5225vock\logs\debug.log
2025-03-05 21:47:03,834 INFO    Thread-17 (_run_job):27272 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_214703-5225vock\logs\debug-internal.log
2025-03-05 21:47:03,834 INFO    Thread-17 (_run_job):27272 [wandb_init.py:init():761] calling init triggers
2025-03-05 21:47:03,834 INFO    Thread-17 (_run_job):27272 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'tanh', 'batch_size': 16, 'epochs': 5, 'hidden_layers': 3, 'hidden_size': 128, 'learning_rate': 0.001, 'optimizer': 'sgd', 'weight_decay': 0.5, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-05 21:47:03,834 INFO    Thread-17 (_run_job):27272 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 21:47:03,834 ERROR   Thread-17 (_run_job):27272 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 21:47:03,842 INFO    Thread-17 (_run_job):27272 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/DLA1/07etksak
2025-03-05 21:47:08,876 INFO    MainThread:27272 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 21:47:08,876 INFO    MainThread:27272 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 21:49:43,790 INFO    MainThread:27272 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 21:49:43,842 INFO    MainThread:27272 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 21:49:43,842 INFO    MainThread:27272 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 21:49:44,610 INFO    MainThread:27272 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 21:49:44,650 INFO    MainThread:27272 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 21:49:44,650 INFO    MainThread:27272 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 21:49:44,807 INFO    MainThread:27272 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 21:49:44,855 INFO    MainThread:27272 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 21:49:44,856 INFO    MainThread:27272 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 21:49:45,464 INFO    MainThread:27272 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 21:49:45,499 INFO    MainThread:27272 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 21:49:45,501 INFO    MainThread:27272 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 21:49:46,545 INFO    MainThread:27272 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 21:49:46,600 INFO    MainThread:27272 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 21:49:46,600 INFO    MainThread:27272 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 21:49:47,126 INFO    MainThread:27272 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 21:49:47,174 INFO    MainThread:27272 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 21:49:47,175 INFO    MainThread:27272 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 21:49:47,334 INFO    MainThread:27272 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 21:49:47,375 INFO    MainThread:27272 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 21:49:47,378 INFO    MainThread:27272 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 21:49:47,765 INFO    MainThread:27272 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 21:49:47,799 INFO    MainThread:27272 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 21:49:47,801 INFO    MainThread:27272 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 21:49:48,845 INFO    MainThread:27272 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 21:49:48,879 INFO    MainThread:27272 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 21:49:48,879 INFO    MainThread:27272 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 21:49:49,092 INFO    MainThread:27272 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 21:49:49,140 INFO    MainThread:27272 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 21:49:49,141 INFO    MainThread:27272 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 21:49:53,993 INFO    MainThread:27272 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 21:49:54,035 INFO    MainThread:27272 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 21:49:54,035 INFO    MainThread:27272 [wandb_init.py:_pause_backend():564] pausing backend
