2025-03-05 21:43:59,526 INFO    MainThread:18620 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 21:43:59,526 INFO    MainThread:18620 [wandb_setup.py:_flush():67] Configure stats pid to 18620
2025-03-05 21:43:59,527 INFO    MainThread:18620 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 21:43:59,527 INFO    MainThread:18620 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 21:43:59,527 INFO    MainThread:18620 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 21:43:59,527 INFO    MainThread:18620 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_214359-qs8nje60\logs\debug.log
2025-03-05 21:43:59,527 INFO    MainThread:18620 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_214359-qs8nje60\logs\debug-internal.log
2025-03-05 21:43:59,527 INFO    MainThread:18620 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000018DAE127AD0>
2025-03-05 21:43:59,528 INFO    MainThread:18620 [wandb_init.py:init():761] calling init triggers
2025-03-05 21:43:59,528 INFO    MainThread:18620 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-05 21:43:59,528 INFO    MainThread:18620 [wandb_init.py:init():784] starting backend
2025-03-05 21:43:59,528 INFO    MainThread:18620 [wandb_init.py:init():788] sending inform_init request
2025-03-05 21:43:59,543 INFO    MainThread:18620 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-03-05 21:43:59,544 INFO    MainThread:18620 [wandb_init.py:init():803] backend started and connected
2025-03-05 21:43:59,546 INFO    MainThread:18620 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-05 21:43:59,558 INFO    MainThread:18620 [wandb_run.py:_label_probe_notebook():1214] Unable to probe notebook: 'charmap' codec can't decode byte 0x81 in position 19920: character maps to <undefined>
2025-03-05 21:43:59,558 INFO    MainThread:18620 [wandb_init.py:init():896] updated telemetry
2025-03-05 21:43:59,806 INFO    MainThread:18620 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-05 21:44:01,237 INFO    MainThread:18620 [wandb_init.py:init():995] starting run threads in backend
2025-03-05 21:44:01,569 INFO    MainThread:18620 [wandb_run.py:_console_start():2377] atexit reg
2025-03-05 21:44:01,570 INFO    MainThread:18620 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-05 21:44:01,570 INFO    MainThread:18620 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-05 21:44:01,570 INFO    MainThread:18620 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-05 21:44:01,574 INFO    MainThread:18620 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-05 21:44:02,183 INFO    MainThread:18620 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 21:44:02,184 INFO    MainThread:18620 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 21:44:06,519 INFO    MainThread:18620 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 21:44:06,522 INFO    MainThread:18620 [pyagent.py:run():322] Starting sweep agent: entity=None, project=None, count=None
2025-03-05 21:44:07,366 WARNING MsgRouterThr:18620 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-05 21:44:07,370 INFO    MsgRouterThr:18620 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
2025-03-05 21:44:08,783 INFO    Thread-14 (_run_job):18620 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 21:44:08,783 INFO    Thread-14 (_run_job):18620 [wandb_setup.py:_flush():67] Configure stats pid to 18620
2025-03-05 21:44:08,783 INFO    Thread-14 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 21:44:08,783 INFO    Thread-14 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 21:44:08,783 INFO    Thread-14 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 21:44:08,783 INFO    Thread-14 (_run_job):18620 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_214408-g54uht0w\logs\debug.log
2025-03-05 21:44:08,785 INFO    Thread-14 (_run_job):18620 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_214408-g54uht0w\logs\debug-internal.log
2025-03-05 21:44:08,785 INFO    Thread-14 (_run_job):18620 [wandb_init.py:init():761] calling init triggers
2025-03-05 21:44:08,785 INFO    Thread-14 (_run_job):18620 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 16, 'epochs': 10, 'hidden_layers': 4, 'hidden_size': 64, 'learning_rate': 0.0001, 'optimizer': 'rmsprop', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-05 21:44:08,785 INFO    Thread-14 (_run_job):18620 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 21:44:08,785 ERROR   Thread-14 (_run_job):18620 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 21:44:08,801 INFO    Thread-14 (_run_job):18620 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/DLA1/qs8nje60
2025-03-05 21:44:12,843 INFO    Thread-17 (_run_job):18620 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 21:44:12,843 INFO    Thread-17 (_run_job):18620 [wandb_setup.py:_flush():67] Configure stats pid to 18620
2025-03-05 21:44:12,843 INFO    Thread-17 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 21:44:12,843 INFO    Thread-17 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 21:44:12,843 INFO    Thread-17 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 21:44:12,843 INFO    Thread-17 (_run_job):18620 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_214412-tedxbc24\logs\debug.log
2025-03-05 21:44:12,843 INFO    Thread-17 (_run_job):18620 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_214412-tedxbc24\logs\debug-internal.log
2025-03-05 21:44:12,843 INFO    Thread-17 (_run_job):18620 [wandb_init.py:init():761] calling init triggers
2025-03-05 21:44:12,843 INFO    Thread-17 (_run_job):18620 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 16, 'epochs': 5, 'hidden_layers': 4, 'hidden_size': 64, 'learning_rate': 0.0001, 'optimizer': 'sgd', 'weight_decay': 0, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-05 21:44:12,843 INFO    Thread-17 (_run_job):18620 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 21:44:12,843 ERROR   Thread-17 (_run_job):18620 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 21:44:12,852 INFO    Thread-17 (_run_job):18620 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/DLA1/qs8nje60
2025-03-05 21:44:22,953 INFO    Thread-20 (_run_job):18620 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 21:44:22,954 INFO    Thread-20 (_run_job):18620 [wandb_setup.py:_flush():67] Configure stats pid to 18620
2025-03-05 21:44:22,954 INFO    Thread-20 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 21:44:22,954 INFO    Thread-20 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 21:44:22,954 INFO    Thread-20 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 21:44:22,954 INFO    Thread-20 (_run_job):18620 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_214422-bnc6ddut\logs\debug.log
2025-03-05 21:44:22,954 INFO    Thread-20 (_run_job):18620 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_214422-bnc6ddut\logs\debug-internal.log
2025-03-05 21:44:22,954 INFO    Thread-20 (_run_job):18620 [wandb_init.py:init():761] calling init triggers
2025-03-05 21:44:22,955 INFO    Thread-20 (_run_job):18620 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 16, 'epochs': 5, 'hidden_layers': 5, 'hidden_size': 64, 'learning_rate': 0.001, 'optimizer': 'momentum', 'weight_decay': 0, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-05 21:44:22,955 INFO    Thread-20 (_run_job):18620 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 21:44:22,955 ERROR   Thread-20 (_run_job):18620 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 21:44:22,961 INFO    Thread-20 (_run_job):18620 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/DLA1/qs8nje60
2025-03-05 21:44:23,939 INFO    Thread-23 (_run_job):18620 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 21:44:23,939 INFO    Thread-23 (_run_job):18620 [wandb_setup.py:_flush():67] Configure stats pid to 18620
2025-03-05 21:44:23,939 INFO    Thread-23 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 21:44:23,939 INFO    Thread-23 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 21:44:23,939 INFO    Thread-23 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 21:44:23,939 INFO    Thread-23 (_run_job):18620 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_214423-6qr0g89k\logs\debug.log
2025-03-05 21:44:23,940 INFO    Thread-23 (_run_job):18620 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_214423-6qr0g89k\logs\debug-internal.log
2025-03-05 21:44:23,940 INFO    Thread-23 (_run_job):18620 [wandb_init.py:init():761] calling init triggers
2025-03-05 21:44:23,940 INFO    Thread-23 (_run_job):18620 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 16, 'epochs': 10, 'hidden_layers': 5, 'hidden_size': 128, 'learning_rate': 0.0001, 'optimizer': 'sgd', 'weight_decay': 0.5, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-05 21:44:23,940 INFO    Thread-23 (_run_job):18620 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 21:44:23,940 ERROR   Thread-23 (_run_job):18620 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 21:44:23,946 INFO    Thread-23 (_run_job):18620 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/DLA1/qs8nje60
2025-03-05 21:44:34,059 INFO    Thread-26 (_run_job):18620 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 21:44:34,060 INFO    Thread-26 (_run_job):18620 [wandb_setup.py:_flush():67] Configure stats pid to 18620
2025-03-05 21:44:34,060 INFO    Thread-26 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 21:44:34,060 INFO    Thread-26 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 21:44:34,060 INFO    Thread-26 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 21:44:34,060 INFO    Thread-26 (_run_job):18620 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_214434-zgqq5698\logs\debug.log
2025-03-05 21:44:34,061 INFO    Thread-26 (_run_job):18620 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_214434-zgqq5698\logs\debug-internal.log
2025-03-05 21:44:34,061 INFO    Thread-26 (_run_job):18620 [wandb_init.py:init():761] calling init triggers
2025-03-05 21:44:34,061 INFO    Thread-26 (_run_job):18620 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'tanh', 'batch_size': 32, 'epochs': 5, 'hidden_layers': 3, 'hidden_size': 128, 'learning_rate': 0.001, 'optimizer': 'sgd', 'weight_decay': 0.0005, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-05 21:44:34,061 INFO    Thread-26 (_run_job):18620 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 21:44:34,062 ERROR   Thread-26 (_run_job):18620 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 21:44:34,071 INFO    Thread-26 (_run_job):18620 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/DLA1/qs8nje60
2025-03-05 21:44:34,772 INFO    Thread-29 (_run_job):18620 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 21:44:34,772 INFO    Thread-29 (_run_job):18620 [wandb_setup.py:_flush():67] Configure stats pid to 18620
2025-03-05 21:44:34,772 INFO    Thread-29 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 21:44:34,772 INFO    Thread-29 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 21:44:34,773 INFO    Thread-29 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 21:44:34,773 INFO    Thread-29 (_run_job):18620 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_214434-7o8qhruv\logs\debug.log
2025-03-05 21:44:34,773 INFO    Thread-29 (_run_job):18620 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_214434-7o8qhruv\logs\debug-internal.log
2025-03-05 21:44:34,774 INFO    Thread-29 (_run_job):18620 [wandb_init.py:init():761] calling init triggers
2025-03-05 21:44:34,774 INFO    Thread-29 (_run_job):18620 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 64, 'epochs': 10, 'hidden_layers': 3, 'hidden_size': 64, 'learning_rate': 0.0001, 'optimizer': 'rmsprop', 'weight_decay': 0.0005, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-05 21:44:34,774 INFO    Thread-29 (_run_job):18620 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 21:44:34,774 ERROR   Thread-29 (_run_job):18620 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 21:44:34,785 INFO    Thread-29 (_run_job):18620 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/DLA1/qs8nje60
2025-03-05 21:44:44,904 INFO    Thread-32 (_run_job):18620 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 21:44:44,904 INFO    Thread-32 (_run_job):18620 [wandb_setup.py:_flush():67] Configure stats pid to 18620
2025-03-05 21:44:44,904 INFO    Thread-32 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 21:44:44,904 INFO    Thread-32 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 21:44:44,904 INFO    Thread-32 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 21:44:44,904 INFO    Thread-32 (_run_job):18620 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_214444-jk7zv8sx\logs\debug.log
2025-03-05 21:44:44,905 INFO    Thread-32 (_run_job):18620 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_214444-jk7zv8sx\logs\debug-internal.log
2025-03-05 21:44:44,905 INFO    Thread-32 (_run_job):18620 [wandb_init.py:init():761] calling init triggers
2025-03-05 21:44:44,905 INFO    Thread-32 (_run_job):18620 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 16, 'epochs': 5, 'hidden_layers': 5, 'hidden_size': 64, 'learning_rate': 0.001, 'optimizer': 'nesterov', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-05 21:44:44,905 INFO    Thread-32 (_run_job):18620 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 21:44:44,905 ERROR   Thread-32 (_run_job):18620 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 21:44:44,911 INFO    Thread-32 (_run_job):18620 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/DLA1/qs8nje60
2025-03-05 21:44:45,566 INFO    Thread-35 (_run_job):18620 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 21:44:45,567 INFO    Thread-35 (_run_job):18620 [wandb_setup.py:_flush():67] Configure stats pid to 18620
2025-03-05 21:44:45,567 INFO    Thread-35 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 21:44:45,567 INFO    Thread-35 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 21:44:45,567 INFO    Thread-35 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 21:44:45,567 INFO    Thread-35 (_run_job):18620 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_214445-yok7w26s\logs\debug.log
2025-03-05 21:44:45,568 INFO    Thread-35 (_run_job):18620 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_214445-yok7w26s\logs\debug-internal.log
2025-03-05 21:44:45,568 INFO    Thread-35 (_run_job):18620 [wandb_init.py:init():761] calling init triggers
2025-03-05 21:44:45,568 INFO    Thread-35 (_run_job):18620 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 64, 'epochs': 5, 'hidden_layers': 4, 'hidden_size': 64, 'learning_rate': 0.0001, 'optimizer': 'adam', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-05 21:44:45,569 INFO    Thread-35 (_run_job):18620 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 21:44:45,569 ERROR   Thread-35 (_run_job):18620 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 21:44:45,576 INFO    Thread-35 (_run_job):18620 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/DLA1/qs8nje60
2025-03-05 21:44:55,760 INFO    Thread-38 (_run_job):18620 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 21:44:55,760 INFO    Thread-38 (_run_job):18620 [wandb_setup.py:_flush():67] Configure stats pid to 18620
2025-03-05 21:44:55,760 INFO    Thread-38 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 21:44:55,760 INFO    Thread-38 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 21:44:55,761 INFO    Thread-38 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 21:44:55,761 INFO    Thread-38 (_run_job):18620 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_214455-yrqkdg14\logs\debug.log
2025-03-05 21:44:55,761 INFO    Thread-38 (_run_job):18620 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_214455-yrqkdg14\logs\debug-internal.log
2025-03-05 21:44:55,762 INFO    Thread-38 (_run_job):18620 [wandb_init.py:init():761] calling init triggers
2025-03-05 21:44:55,762 INFO    Thread-38 (_run_job):18620 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'tanh', 'batch_size': 64, 'epochs': 5, 'hidden_layers': 5, 'hidden_size': 64, 'learning_rate': 0.001, 'optimizer': 'momentum', 'weight_decay': 0.0005, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-05 21:44:55,762 INFO    Thread-38 (_run_job):18620 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 21:44:55,762 ERROR   Thread-38 (_run_job):18620 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 21:44:55,775 INFO    Thread-38 (_run_job):18620 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/DLA1/qs8nje60
2025-03-05 21:44:56,671 INFO    Thread-41 (_run_job):18620 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 21:44:56,671 INFO    Thread-41 (_run_job):18620 [wandb_setup.py:_flush():67] Configure stats pid to 18620
2025-03-05 21:44:56,672 INFO    Thread-41 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 21:44:56,672 INFO    Thread-41 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 21:44:56,672 INFO    Thread-41 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 21:44:56,672 INFO    Thread-41 (_run_job):18620 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_214456-p4xrb4xx\logs\debug.log
2025-03-05 21:44:56,673 INFO    Thread-41 (_run_job):18620 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_214456-p4xrb4xx\logs\debug-internal.log
2025-03-05 21:44:56,673 INFO    Thread-41 (_run_job):18620 [wandb_init.py:init():761] calling init triggers
2025-03-05 21:44:56,674 INFO    Thread-41 (_run_job):18620 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 32, 'epochs': 10, 'hidden_layers': 3, 'hidden_size': 64, 'learning_rate': 0.0001, 'optimizer': 'nesterov', 'weight_decay': 0.0005, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-05 21:44:56,674 INFO    Thread-41 (_run_job):18620 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 21:44:56,674 ERROR   Thread-41 (_run_job):18620 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 21:44:56,683 INFO    Thread-41 (_run_job):18620 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/DLA1/qs8nje60
2025-03-05 21:45:06,795 INFO    Thread-44 (_run_job):18620 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 21:45:06,795 INFO    Thread-44 (_run_job):18620 [wandb_setup.py:_flush():67] Configure stats pid to 18620
2025-03-05 21:45:06,795 INFO    Thread-44 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 21:45:06,796 INFO    Thread-44 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 21:45:06,796 INFO    Thread-44 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 21:45:06,796 INFO    Thread-44 (_run_job):18620 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_214506-z3oq6ymb\logs\debug.log
2025-03-05 21:45:06,797 INFO    Thread-44 (_run_job):18620 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_214506-z3oq6ymb\logs\debug-internal.log
2025-03-05 21:45:06,797 INFO    Thread-44 (_run_job):18620 [wandb_init.py:init():761] calling init triggers
2025-03-05 21:45:06,797 INFO    Thread-44 (_run_job):18620 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'tanh', 'batch_size': 64, 'epochs': 5, 'hidden_layers': 3, 'hidden_size': 64, 'learning_rate': 0.0001, 'optimizer': 'momentum', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-05 21:45:06,797 INFO    Thread-44 (_run_job):18620 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 21:45:06,798 ERROR   Thread-44 (_run_job):18620 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 21:45:06,805 INFO    Thread-44 (_run_job):18620 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/DLA1/qs8nje60
2025-03-05 21:45:07,662 INFO    Thread-47 (_run_job):18620 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 21:45:07,663 INFO    Thread-47 (_run_job):18620 [wandb_setup.py:_flush():67] Configure stats pid to 18620
2025-03-05 21:45:07,663 INFO    Thread-47 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 21:45:07,663 INFO    Thread-47 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 21:45:07,663 INFO    Thread-47 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 21:45:07,664 INFO    Thread-47 (_run_job):18620 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_214507-7idj04jl\logs\debug.log
2025-03-05 21:45:07,664 INFO    Thread-47 (_run_job):18620 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_214507-7idj04jl\logs\debug-internal.log
2025-03-05 21:45:07,664 INFO    Thread-47 (_run_job):18620 [wandb_init.py:init():761] calling init triggers
2025-03-05 21:45:07,664 INFO    Thread-47 (_run_job):18620 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 16, 'epochs': 10, 'hidden_layers': 4, 'hidden_size': 128, 'learning_rate': 0.0001, 'optimizer': 'momentum', 'weight_decay': 0.5, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-05 21:45:07,664 INFO    Thread-47 (_run_job):18620 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 21:45:07,665 ERROR   Thread-47 (_run_job):18620 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 21:45:07,671 INFO    Thread-47 (_run_job):18620 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/DLA1/qs8nje60
2025-03-05 21:45:17,776 INFO    Thread-50 (_run_job):18620 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 21:45:17,776 INFO    Thread-50 (_run_job):18620 [wandb_setup.py:_flush():67] Configure stats pid to 18620
2025-03-05 21:45:17,776 INFO    Thread-50 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 21:45:17,776 INFO    Thread-50 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 21:45:17,777 INFO    Thread-50 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 21:45:17,777 INFO    Thread-50 (_run_job):18620 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_214517-jh01iap6\logs\debug.log
2025-03-05 21:45:17,777 INFO    Thread-50 (_run_job):18620 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_214517-jh01iap6\logs\debug-internal.log
2025-03-05 21:45:17,778 INFO    Thread-50 (_run_job):18620 [wandb_init.py:init():761] calling init triggers
2025-03-05 21:45:17,778 INFO    Thread-50 (_run_job):18620 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 32, 'epochs': 5, 'hidden_layers': 3, 'hidden_size': 64, 'learning_rate': 0.001, 'optimizer': 'nadam', 'weight_decay': 0.0005, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-05 21:45:17,778 INFO    Thread-50 (_run_job):18620 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 21:45:17,778 ERROR   Thread-50 (_run_job):18620 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 21:45:17,785 INFO    Thread-50 (_run_job):18620 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/DLA1/qs8nje60
2025-03-05 21:45:18,693 INFO    Thread-53 (_run_job):18620 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 21:45:18,694 INFO    Thread-53 (_run_job):18620 [wandb_setup.py:_flush():67] Configure stats pid to 18620
2025-03-05 21:45:18,694 INFO    Thread-53 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 21:45:18,694 INFO    Thread-53 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 21:45:18,695 INFO    Thread-53 (_run_job):18620 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 21:45:18,695 INFO    Thread-53 (_run_job):18620 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_214518-vqbxpwgm\logs\debug.log
2025-03-05 21:45:18,696 INFO    Thread-53 (_run_job):18620 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_214518-vqbxpwgm\logs\debug-internal.log
2025-03-05 21:45:18,696 INFO    Thread-53 (_run_job):18620 [wandb_init.py:init():761] calling init triggers
2025-03-05 21:45:18,696 INFO    Thread-53 (_run_job):18620 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 32, 'epochs': 5, 'hidden_layers': 4, 'hidden_size': 32, 'learning_rate': 0.001, 'optimizer': 'rmsprop', 'weight_decay': 0.0005, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-05 21:45:18,697 INFO    Thread-53 (_run_job):18620 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 21:45:18,697 ERROR   Thread-53 (_run_job):18620 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 21:45:18,706 INFO    Thread-53 (_run_job):18620 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/DLA1/qs8nje60
2025-03-05 21:45:23,742 INFO    MainThread:18620 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 21:45:23,742 INFO    MainThread:18620 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 21:45:29,756 INFO    MainThread:18620 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 21:45:29,804 INFO    MainThread:18620 [pyagent.py:run():322] Starting sweep agent: entity=da24m014-iit-madras, project=DLA1, count=None
2025-03-05 21:45:33,590 ERROR   MainThread:18620 [internal_api.py:execute():402] 404 response executing GraphQL.
2025-03-05 21:45:33,590 ERROR   MainThread:18620 [internal_api.py:execute():403] {"errors":[{"message":"could not find sweep da24m014-iit-madras/DLA1/yqx7dhzz during createAgent","path":["createAgent"]}],"data":{"createAgent":null}}
2025-03-05 21:45:34,268 INFO    MainThread:18620 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 21:45:34,268 INFO    MainThread:18620 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 21:45:39,807 INFO    MainThread:18620 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 21:45:39,875 INFO    MainThread:18620 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 21:45:39,877 INFO    MainThread:18620 [wandb_init.py:_pause_backend():564] pausing backend
