2025-03-05 09:13:50,084 INFO    MainThread:31836 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_091350-tx0z57wi\logs\debug.log
2025-03-05 09:13:50,085 INFO    MainThread:31836 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_091350-tx0z57wi\logs\debug-internal.log
2025-03-05 09:13:50,085 INFO    MainThread:31836 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002D067223A50>
2025-03-05 09:13:50,085 INFO    MainThread:31836 [wandb_init.py:init():761] calling init triggers
2025-03-05 09:13:50,086 INFO    MainThread:31836 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-05 09:13:50,086 INFO    MainThread:31836 [wandb_init.py:init():784] starting backend
2025-03-05 09:13:50,086 INFO    MainThread:31836 [wandb_init.py:init():788] sending inform_init request
2025-03-05 09:13:50,087 INFO    MainThread:31836 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-03-05 09:13:50,088 INFO    MainThread:31836 [wandb_init.py:init():803] backend started and connected
2025-03-05 09:13:50,091 INFO    MainThread:31836 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-05 09:13:50,106 INFO    MainThread:31836 [wandb_init.py:init():896] updated telemetry
2025-03-05 09:13:50,192 INFO    MainThread:31836 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-05 09:13:52,043 INFO    MainThread:31836 [wandb_init.py:init():995] starting run threads in backend
2025-03-05 09:13:52,283 INFO    MainThread:31836 [wandb_run.py:_console_start():2377] atexit reg
2025-03-05 09:13:52,284 INFO    MainThread:31836 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-05 09:13:52,284 INFO    MainThread:31836 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-05 09:13:52,284 INFO    MainThread:31836 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-05 09:13:52,284 INFO    MainThread:31836 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-05 09:13:52,868 INFO    MainThread:31836 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 09:13:52,868 INFO    MainThread:31836 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 09:13:58,061 INFO    MainThread:31836 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 09:13:58,065 INFO    MainThread:31836 [pyagent.py:run():322] Starting sweep agent: entity=None, project=None, count=None
2025-03-05 09:13:58,993 WARNING MsgRouterThr:31836 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-05 09:13:58,995 INFO    MsgRouterThr:31836 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
2025-03-05 09:14:00,468 INFO    Thread-16 (_run_job):31836 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 09:14:00,468 INFO    Thread-16 (_run_job):31836 [wandb_setup.py:_flush():67] Configure stats pid to 31836
2025-03-05 09:14:00,468 INFO    Thread-16 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 09:14:00,468 INFO    Thread-16 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 09:14:00,468 INFO    Thread-16 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 09:14:00,468 INFO    Thread-16 (_run_job):31836 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_091400-tqpjeadg\logs\debug.log
2025-03-05 09:14:00,468 INFO    Thread-16 (_run_job):31836 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_091400-tqpjeadg\logs\debug-internal.log
2025-03-05 09:14:00,469 INFO    Thread-16 (_run_job):31836 [wandb_init.py:init():761] calling init triggers
2025-03-05 09:14:00,469 INFO    Thread-16 (_run_job):31836 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 16, 'epochs': 5, 'hidden_layers': 2, 'hidden_size': 64, 'learning_rate': 0.001, 'optimizer': 'sgd', 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-05 09:14:00,469 INFO    Thread-16 (_run_job):31836 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 09:14:00,469 ERROR   Thread-16 (_run_job):31836 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 09:14:00,479 INFO    Thread-16 (_run_job):31836 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/tx0z57wi
2025-03-05 09:14:04,448 INFO    Thread-19 (_run_job):31836 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 09:14:04,449 INFO    Thread-19 (_run_job):31836 [wandb_setup.py:_flush():67] Configure stats pid to 31836
2025-03-05 09:14:04,449 INFO    Thread-19 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 09:14:04,449 INFO    Thread-19 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 09:14:04,449 INFO    Thread-19 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 09:14:04,449 INFO    Thread-19 (_run_job):31836 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_091404-fxkx8u6l\logs\debug.log
2025-03-05 09:14:04,449 INFO    Thread-19 (_run_job):31836 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_091404-fxkx8u6l\logs\debug-internal.log
2025-03-05 09:14:04,450 INFO    Thread-19 (_run_job):31836 [wandb_init.py:init():761] calling init triggers
2025-03-05 09:14:04,450 INFO    Thread-19 (_run_job):31836 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 32, 'epochs': 10, 'hidden_layers': 2, 'hidden_size': 32, 'learning_rate': 0.1, 'optimizer': 'momentum', 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-05 09:14:04,450 INFO    Thread-19 (_run_job):31836 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 09:14:04,450 ERROR   Thread-19 (_run_job):31836 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 09:14:04,457 INFO    Thread-19 (_run_job):31836 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/tx0z57wi
2025-03-05 09:14:14,552 INFO    Thread-22 (_run_job):31836 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 09:14:14,553 INFO    Thread-22 (_run_job):31836 [wandb_setup.py:_flush():67] Configure stats pid to 31836
2025-03-05 09:14:14,553 INFO    Thread-22 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 09:14:14,553 INFO    Thread-22 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 09:14:14,553 INFO    Thread-22 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 09:14:14,553 INFO    Thread-22 (_run_job):31836 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_091414-9s8429av\logs\debug.log
2025-03-05 09:14:14,554 INFO    Thread-22 (_run_job):31836 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_091414-9s8429av\logs\debug-internal.log
2025-03-05 09:14:14,554 INFO    Thread-22 (_run_job):31836 [wandb_init.py:init():761] calling init triggers
2025-03-05 09:14:14,554 INFO    Thread-22 (_run_job):31836 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 16, 'epochs': 10, 'hidden_layers': 3, 'hidden_size': 32, 'learning_rate': 0.001, 'optimizer': 'momentum', 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-05 09:14:14,554 INFO    Thread-22 (_run_job):31836 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 09:14:14,554 ERROR   Thread-22 (_run_job):31836 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 09:14:14,561 INFO    Thread-22 (_run_job):31836 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/tx0z57wi
2025-03-05 09:14:15,252 INFO    Thread-25 (_run_job):31836 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 09:14:15,253 INFO    Thread-25 (_run_job):31836 [wandb_setup.py:_flush():67] Configure stats pid to 31836
2025-03-05 09:14:15,253 INFO    Thread-25 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 09:14:15,253 INFO    Thread-25 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 09:14:15,253 INFO    Thread-25 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 09:14:15,253 INFO    Thread-25 (_run_job):31836 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_091415-07dvqg8m\logs\debug.log
2025-03-05 09:14:15,254 INFO    Thread-25 (_run_job):31836 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_091415-07dvqg8m\logs\debug-internal.log
2025-03-05 09:14:15,254 INFO    Thread-25 (_run_job):31836 [wandb_init.py:init():761] calling init triggers
2025-03-05 09:14:15,254 INFO    Thread-25 (_run_job):31836 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 32, 'epochs': 10, 'hidden_layers': 2, 'hidden_size': 32, 'learning_rate': 0.01, 'optimizer': 'sgd', 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-05 09:14:15,254 INFO    Thread-25 (_run_job):31836 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 09:14:15,254 ERROR   Thread-25 (_run_job):31836 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 09:14:15,261 INFO    Thread-25 (_run_job):31836 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/tx0z57wi
2025-03-05 09:14:25,368 INFO    Thread-28 (_run_job):31836 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 09:14:25,369 INFO    Thread-28 (_run_job):31836 [wandb_setup.py:_flush():67] Configure stats pid to 31836
2025-03-05 09:14:25,369 INFO    Thread-28 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 09:14:25,369 INFO    Thread-28 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 09:14:25,369 INFO    Thread-28 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 09:14:25,369 INFO    Thread-28 (_run_job):31836 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_091425-d6y4egzt\logs\debug.log
2025-03-05 09:14:25,370 INFO    Thread-28 (_run_job):31836 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_091425-d6y4egzt\logs\debug-internal.log
2025-03-05 09:14:25,370 INFO    Thread-28 (_run_job):31836 [wandb_init.py:init():761] calling init triggers
2025-03-05 09:14:25,370 INFO    Thread-28 (_run_job):31836 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 16, 'epochs': 10, 'hidden_layers': 2, 'hidden_size': 64, 'learning_rate': 0.01, 'optimizer': 'momentum', 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-05 09:14:25,370 INFO    Thread-28 (_run_job):31836 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 09:14:25,370 ERROR   Thread-28 (_run_job):31836 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 09:14:25,378 INFO    Thread-28 (_run_job):31836 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/tx0z57wi
2025-03-05 09:14:26,230 INFO    Thread-31 (_run_job):31836 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 09:14:26,231 INFO    Thread-31 (_run_job):31836 [wandb_setup.py:_flush():67] Configure stats pid to 31836
2025-03-05 09:14:26,231 INFO    Thread-31 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 09:14:26,231 INFO    Thread-31 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 09:14:26,231 INFO    Thread-31 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 09:14:26,231 INFO    Thread-31 (_run_job):31836 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_091426-yg21crtx\logs\debug.log
2025-03-05 09:14:26,232 INFO    Thread-31 (_run_job):31836 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_091426-yg21crtx\logs\debug-internal.log
2025-03-05 09:14:26,232 INFO    Thread-31 (_run_job):31836 [wandb_init.py:init():761] calling init triggers
2025-03-05 09:14:26,232 INFO    Thread-31 (_run_job):31836 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 16, 'epochs': 10, 'hidden_layers': 2, 'hidden_size': 64, 'learning_rate': 0.001, 'optimizer': 'sgd', 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-05 09:14:26,232 INFO    Thread-31 (_run_job):31836 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 09:14:26,233 ERROR   Thread-31 (_run_job):31836 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 09:14:26,239 INFO    Thread-31 (_run_job):31836 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/tx0z57wi
2025-03-05 09:14:36,347 INFO    Thread-34 (_run_job):31836 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 09:14:36,347 INFO    Thread-34 (_run_job):31836 [wandb_setup.py:_flush():67] Configure stats pid to 31836
2025-03-05 09:14:36,347 INFO    Thread-34 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 09:14:36,347 INFO    Thread-34 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 09:14:36,347 INFO    Thread-34 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 09:14:36,348 INFO    Thread-34 (_run_job):31836 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_091436-u5iltnw3\logs\debug.log
2025-03-05 09:14:36,348 INFO    Thread-34 (_run_job):31836 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_091436-u5iltnw3\logs\debug-internal.log
2025-03-05 09:14:36,348 INFO    Thread-34 (_run_job):31836 [wandb_init.py:init():761] calling init triggers
2025-03-05 09:14:36,348 INFO    Thread-34 (_run_job):31836 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 64, 'epochs': 5, 'hidden_layers': 2, 'hidden_size': 64, 'learning_rate': 0.1, 'optimizer': 'momentum', 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-05 09:14:36,348 INFO    Thread-34 (_run_job):31836 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 09:14:36,348 ERROR   Thread-34 (_run_job):31836 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 09:14:36,354 INFO    Thread-34 (_run_job):31836 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/tx0z57wi
2025-03-05 09:14:46,455 INFO    Thread-37 (_run_job):31836 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 09:14:46,455 INFO    Thread-37 (_run_job):31836 [wandb_setup.py:_flush():67] Configure stats pid to 31836
2025-03-05 09:14:46,455 INFO    Thread-37 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 09:14:46,456 INFO    Thread-37 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 09:14:46,456 INFO    Thread-37 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 09:14:46,456 INFO    Thread-37 (_run_job):31836 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_091446-v7fwmaqu\logs\debug.log
2025-03-05 09:14:46,457 INFO    Thread-37 (_run_job):31836 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_091446-v7fwmaqu\logs\debug-internal.log
2025-03-05 09:14:46,457 INFO    Thread-37 (_run_job):31836 [wandb_init.py:init():761] calling init triggers
2025-03-05 09:14:46,457 INFO    Thread-37 (_run_job):31836 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 32, 'epochs': 10, 'hidden_layers': 3, 'hidden_size': 32, 'learning_rate': 0.1, 'optimizer': 'sgd', 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-05 09:14:46,457 INFO    Thread-37 (_run_job):31836 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 09:14:46,457 ERROR   Thread-37 (_run_job):31836 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 09:14:46,463 INFO    Thread-37 (_run_job):31836 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/tx0z57wi
2025-03-05 09:14:47,515 INFO    Thread-40 (_run_job):31836 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 09:14:47,516 INFO    Thread-40 (_run_job):31836 [wandb_setup.py:_flush():67] Configure stats pid to 31836
2025-03-05 09:14:47,516 INFO    Thread-40 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 09:14:47,516 INFO    Thread-40 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 09:14:47,516 INFO    Thread-40 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 09:14:47,516 INFO    Thread-40 (_run_job):31836 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_091447-fk90h3dg\logs\debug.log
2025-03-05 09:14:47,517 INFO    Thread-40 (_run_job):31836 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_091447-fk90h3dg\logs\debug-internal.log
2025-03-05 09:14:47,517 INFO    Thread-40 (_run_job):31836 [wandb_init.py:init():761] calling init triggers
2025-03-05 09:14:47,517 INFO    Thread-40 (_run_job):31836 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 16, 'epochs': 10, 'hidden_layers': 3, 'hidden_size': 64, 'learning_rate': 0.001, 'optimizer': 'sgd', 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-05 09:14:47,517 INFO    Thread-40 (_run_job):31836 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 09:14:47,518 ERROR   Thread-40 (_run_job):31836 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 09:14:47,524 INFO    Thread-40 (_run_job):31836 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/tx0z57wi
2025-03-05 09:14:57,627 INFO    Thread-43 (_run_job):31836 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 09:14:57,627 INFO    Thread-43 (_run_job):31836 [wandb_setup.py:_flush():67] Configure stats pid to 31836
2025-03-05 09:14:57,627 INFO    Thread-43 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 09:14:57,627 INFO    Thread-43 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 09:14:57,628 INFO    Thread-43 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 09:14:57,628 INFO    Thread-43 (_run_job):31836 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_091457-8mauxknq\logs\debug.log
2025-03-05 09:14:57,628 INFO    Thread-43 (_run_job):31836 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_091457-8mauxknq\logs\debug-internal.log
2025-03-05 09:14:57,628 INFO    Thread-43 (_run_job):31836 [wandb_init.py:init():761] calling init triggers
2025-03-05 09:14:57,629 INFO    Thread-43 (_run_job):31836 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 64, 'epochs': 5, 'hidden_layers': 3, 'hidden_size': 32, 'learning_rate': 0.01, 'optimizer': 'momentum', 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-05 09:14:57,629 INFO    Thread-43 (_run_job):31836 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 09:14:57,629 ERROR   Thread-43 (_run_job):31836 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 09:14:57,636 INFO    Thread-43 (_run_job):31836 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/tx0z57wi
2025-03-05 09:14:58,595 INFO    Thread-46 (_run_job):31836 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 09:14:58,595 INFO    Thread-46 (_run_job):31836 [wandb_setup.py:_flush():67] Configure stats pid to 31836
2025-03-05 09:14:58,596 INFO    Thread-46 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 09:14:58,596 INFO    Thread-46 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 09:14:58,596 INFO    Thread-46 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 09:14:58,596 INFO    Thread-46 (_run_job):31836 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_091458-eahfmzh0\logs\debug.log
2025-03-05 09:14:58,597 INFO    Thread-46 (_run_job):31836 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_091458-eahfmzh0\logs\debug-internal.log
2025-03-05 09:14:58,597 INFO    Thread-46 (_run_job):31836 [wandb_init.py:init():761] calling init triggers
2025-03-05 09:14:58,597 INFO    Thread-46 (_run_job):31836 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 16, 'epochs': 5, 'hidden_layers': 2, 'hidden_size': 64, 'learning_rate': 0.01, 'optimizer': 'sgd', 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-05 09:14:58,597 INFO    Thread-46 (_run_job):31836 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 09:14:58,597 ERROR   Thread-46 (_run_job):31836 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 09:14:58,603 INFO    Thread-46 (_run_job):31836 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/tx0z57wi
2025-03-05 09:15:08,714 INFO    Thread-49 (_run_job):31836 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 09:15:08,716 INFO    Thread-49 (_run_job):31836 [wandb_setup.py:_flush():67] Configure stats pid to 31836
2025-03-05 09:15:08,716 INFO    Thread-49 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 09:15:08,716 INFO    Thread-49 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 09:15:08,716 INFO    Thread-49 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 09:15:08,716 INFO    Thread-49 (_run_job):31836 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_091508-4cf6d0b5\logs\debug.log
2025-03-05 09:15:08,716 INFO    Thread-49 (_run_job):31836 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_091508-4cf6d0b5\logs\debug-internal.log
2025-03-05 09:15:08,716 INFO    Thread-49 (_run_job):31836 [wandb_init.py:init():761] calling init triggers
2025-03-05 09:15:08,716 INFO    Thread-49 (_run_job):31836 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 32, 'epochs': 5, 'hidden_layers': 2, 'hidden_size': 32, 'learning_rate': 0.001, 'optimizer': 'momentum', 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-05 09:15:08,718 INFO    Thread-49 (_run_job):31836 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 09:15:08,718 ERROR   Thread-49 (_run_job):31836 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 09:15:08,725 INFO    Thread-49 (_run_job):31836 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/tx0z57wi
2025-03-05 09:15:09,782 INFO    Thread-52 (_run_job):31836 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 09:15:09,783 INFO    Thread-52 (_run_job):31836 [wandb_setup.py:_flush():67] Configure stats pid to 31836
2025-03-05 09:15:09,783 INFO    Thread-52 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 09:15:09,783 INFO    Thread-52 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 09:15:09,783 INFO    Thread-52 (_run_job):31836 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 09:15:09,784 INFO    Thread-52 (_run_job):31836 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_091509-y9u6sdp0\logs\debug.log
2025-03-05 09:15:09,784 INFO    Thread-52 (_run_job):31836 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_091509-y9u6sdp0\logs\debug-internal.log
2025-03-05 09:15:09,785 INFO    Thread-52 (_run_job):31836 [wandb_init.py:init():761] calling init triggers
2025-03-05 09:15:09,785 INFO    Thread-52 (_run_job):31836 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 64, 'epochs': 10, 'hidden_layers': 2, 'hidden_size': 64, 'learning_rate': 0.01, 'optimizer': 'sgd', 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-05 09:15:09,785 INFO    Thread-52 (_run_job):31836 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 09:15:09,785 ERROR   Thread-52 (_run_job):31836 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 09:15:09,793 INFO    Thread-52 (_run_job):31836 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/tx0z57wi
