2025-03-17 14:58:37,851 INFO    MainThread:872 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-17 14:58:37,851 INFO    MainThread:872 [wandb_setup.py:_flush():67] Configure stats pid to 872
2025-03-17 14:58:37,851 INFO    MainThread:872 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-17 14:58:37,851 INFO    MainThread:872 [wandb_setup.py:_flush():67] Loading settings from D:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-17 14:58:37,851 INFO    MainThread:872 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-17 14:58:37,851 INFO    MainThread:872 [wandb_init.py:setup_run_log_directory():647] Logging user logs to D:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250317_145837-w5j9phwb\logs\debug.log
2025-03-17 14:58:37,851 INFO    MainThread:872 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to D:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250317_145837-w5j9phwb\logs\debug-internal.log
2025-03-17 14:58:37,851 INFO    MainThread:872 [wandb_init.py:init():761] calling init triggers
2025-03-17 14:58:37,851 INFO    MainThread:872 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'dataset': 'fashion_mnist', 'learning_rate': 0.001, 'epochs': 10, 'batch_size': 32, 'loss': 'cross_entropy', 'optimizer': 'adam', 'momentum': 0.9, 'beta': 0.9, 'beta1': 0.9, 'beta2': 0.999, 'epsilon': 1e-06, 'weight_decay': 0.0001, 'weight_init': 'xavier', 'num_layers': 2, 'hidden_size': 128, 'activation': 'tanh', '_wandb': {}}
2025-03-17 14:58:37,851 INFO    MainThread:872 [wandb_init.py:init():784] starting backend
2025-03-17 14:58:37,852 INFO    MainThread:872 [wandb_init.py:init():788] sending inform_init request
2025-03-17 14:58:37,871 INFO    MainThread:872 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-03-17 14:58:37,872 INFO    MainThread:872 [wandb_init.py:init():803] backend started and connected
2025-03-17 14:58:37,875 INFO    MainThread:872 [wandb_init.py:init():896] updated telemetry
2025-03-17 14:58:37,931 INFO    MainThread:872 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-17 14:58:39,889 INFO    MainThread:872 [wandb_init.py:init():995] starting run threads in backend
2025-03-17 14:58:43,282 INFO    MainThread:872 [wandb_run.py:_console_start():2377] atexit reg
2025-03-17 14:58:43,283 INFO    MainThread:872 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-17 14:58:43,283 INFO    MainThread:872 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-17 14:58:43,283 INFO    MainThread:872 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-17 14:58:43,289 INFO    MainThread:872 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-17 14:59:34,186 INFO    MainThread:872 [wandb_run.py:_config_callback():1261] config_cb ('_wandb', 'visualize', 'test_confusion_matrix') {'panel_type': 'Vega2', 'panel_config': {'panelDefId': 'wandb/confusion_matrix/v1', 'fieldSettings': {'Actual': 'Actual', 'Predicted': 'Predicted', 'nPredictions': 'nPredictions'}, 'stringSettings': {'title': 'Confusion Matrix Curve'}, 'transform': {'name': 'tableWithLeafColNames'}, 'userQuery': {'queryFields': [{'name': 'runSets', 'args': [{'name': 'runSets', 'value': '${runSets}'}], 'fields': [{'name': 'id', 'fields': []}, {'name': 'name', 'fields': []}, {'name': '_defaultColorIndex', 'fields': []}, {'name': 'summaryTable', 'args': [{'name': 'tableKey', 'value': 'test_confusion_matrix_table'}], 'fields': []}]}]}}} None
2025-03-17 14:59:35,393 WARNING MsgRouterThr:872 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-17 14:59:35,429 INFO    MsgRouterThr:872 [mailbox.py:close():115] Closing mailbox, abandoning 2 handles.
